---
title: "PTT Movie"
author: "In Bed"
date: "2021/12/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(magrittr)
library(rvest)

url_vec = c()
pageNum = 9511:9460
urls <- paste("https://www.ptt.cc/bbs/movie/index", pageNum,".html", sep="")

crawlURL <- function(url){
  raw_html <- read_html(url)
  article_link_xpath <- "//div[@class='title']/a"
  article_links <- raw_html %>%
    html_nodes(xpath = article_link_xpath) %>%
    html_attr("href")
  article_links <- paste("https://www.ptt.cc", article_links, sep = "")
  return(article_links)
}
```

```{r}
for (i in 1:50){
  url_vec <- c(url_vec, crawlURL(urls[i]))
}
```

```{r}
article_detail <- function(url){
    raw_html <- read_html(url)
    
    # select the css path to locate the data
    author_css <- ".article-metaline:nth-child(1) .article-meta-value"
    title_css <- ".article-metaline-right+ .article-metaline .article-meta-value"
    time_css <- ".article-metaline+ .article-metaline .article-meta-value"
    main_content_css <- "#main-content"
    #ip_css <- ".hl+ .f2"
    push_css <- ".push-tag"
    push_id_css <- ".push-userid"
    push_content_css <- ".push-content"
    push_time_css <- ".push-ipdatetime"
    
    article_detail_info <- list()
    columns <- c(author_css, title_css, time_css, main_content_css, push_css, push_id_css, push_content_css, push_time_css)
    for (i in 1:length(columns)){
        article_content <- raw_html %>%
            html_nodes(css = columns[i]) %>%
            html_text()
        article_detail_info[[i]] <- article_content
    }
    
    names(article_detail_info) <- c("author", "title", "time", "main_content", "push", "push_id", "push_content", "push_time")
    
    # data cleaning process
    article_detail_info$main_content <- article_detail_info$main_content %>%
        gsub(pattern = "\n", ., replacement = "") %>% # 清理斷行符號
        gsub(pattern = "--.+", ., replacement = "") %>% # 去尾
        gsub(pattern = "作者.+:[0-9]{2}\\s[0-9]{4}", ., replacement = "") # 去頭
    #ip_start <- regexpr(pattern = "[0-9]+", article_detail_info$ip)
    #ip_end <- nchar(article_detail_info$ip)
    #article_detail_info$ip <- substr(article_detail_info$ip, start = ip_start, stop = ip_end)
    #article_detail_info$ip <- gsub(pattern = "\n", article_detail_info$ip, replacement = "") # 清理斷行符號
    article_detail_info$push <- gsub(pattern = "\\s", article_detail_info$push, replacement = "")
    article_detail_info$push_id <- gsub(pattern = "\\s", article_detail_info$push_id, replacement = "")
    article_detail_info$push_content <- article_detail_info$push_content %>%
        gsub(pattern = "\\s", ., replacement = "") %>%
        gsub(pattern = ":", ., replacement = "")
    article_detail_info$push_time <- article_detail_info$push_time %>%
        gsub(pattern = "^\\s", ., replacement = "") %>%
        gsub(pattern = "\n", ., replacement = "")
    return(article_detail_info)
}
```



```{r}
article_list = list()
for (i in seq_along(url_vec[1:974])){
  article_list[[i]] <- article_detail(url_vec[i])
}
```


```{r}
post_title_list = c("")
post_content_list = c("")
for (i in 1:974) {
  post_title_list[i] = article_list[[i]]["title"]
  post_content_list[i] = article_list[[i]]["main_content"]
}
which(is.na(post_title_list) == TRUE)
post_title = unlist(post_title_list)
post_content = unlist(post_content_list)
post_content = post_content[-685]

data = as.data.frame(cbind(post_title, post_content))
write.csv(data,"E:/In Bed/研究所/碩一/研究方法與論文寫作/期末報告/crawl.csv")
grep("<", data$post_content, perl = T)
article_data = data

write.table(article_data, file = "crawl.txt", sep = "\t",
            row.names = TRUE, col.names = NA)
```
